name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.11'
          extensions: mbstring, xml, curl
          tools: composer

      - name: Install dep
        run: |
          composer install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0
          registry-url: 'https://registry.npmjs.org'

      - name: Building & Releasing
        run: |
          npm i --omit=dev
          npm run build
          chmod -R 755 ./package/
          cd package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{vars.SMTP_HOST}}
          from-email: ${{vars.SMTP_USER}}
          to-email: para@fagnerjb.com
          username: ${{vars.SMTP_USER}}
          password: ${{secrets.SMTP_PASS}}
          subject: Deploy done
          html: |
            <p>Deploy done: ${{github.ref_name}} in ${{github.repository}}</p>
